# Generated by Django 3.1.7 on 2021-04-02 07:00

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nama Sertifikat')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title pendidikan Kamu')),
                ('long', models.CharField(max_length=255, verbose_name='Lama kamu bersekolah (dalam tahun)')),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Deskripsi Singkat')),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=255, verbose_name='Nama panggilan/sapaan')),
                ('f_name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('w_phone', models.CharField(max_length=255, verbose_name='Nomor handphone / Wa kamu')),
                ('email', models.EmailField(max_length=255)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Deskripsi Singkat')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MySocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.socialmedia')),
            ],
        ),
    ]
