# Generated by Django 3.1.7 on 2021-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_myprofile_prof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='w_phone',
            field=models.CharField(max_length=255, verbose_name='Nomor handphone / Wa kamu +62 (cth: 813xxxxxxxxxx)'),
        ),
        migrations.DeleteModel(
            name='MySocial',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
