# Generated by Django 3.1.7 on 2021-04-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_mysocial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skills',
        ),
    ]
